# Generated by Django 3.2.8 on 2021-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='fuel_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='kms_driven',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='owners',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='present_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='seller_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='selling_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='transmission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_set',
            name='year',
            field=models.IntegerField(),
        ),
    ]
